In [1]:
import os
import pandas as pd

In [2]:

pd.options.display.max_columns = None
os.listdir('../data')

['lat_long.csv',
 'poverty.csv',
 'PovStatsCountry-Series.csv',
 'PovStatsCountry.csv',
 'PovStatsData.csv',
 'PovStatsFootNote.csv',
 'PovStatsSeries.csv']

In [3]:
series = pd.read_csv('../data/PovStatsSeries.csv')
print(series.shape)
series

(64, 21)

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type,Unnamed: 20
0,SI.DST.02ND.20,Poverty: Income distribution,Income share held by second 20%,NaN,Percentage share of income or consumption is t...,%,Annual,NaN,NaN,NaN,"Despite progress in the last decade, the chall...",NaN,The World Bank’s internationally comparable po...,"World Bank, Development Research Group. Data a...",Inequality in the distribution of income is re...,The World Bank Group's goal of promoting share...,NaN,NaN,NaN,CC BY-4.0,NaN
1,SI.DST.03RD.20,Poverty: Income distribution,Income share held by third 20%,NaN,Percentage share of income or consumption is t...,%,Annual,NaN,NaN,NaN,"Despite progress in the last decade, the chall...",NaN,The World Bank’s internationally comparable po...,"World Bank, Development Research Group. Data a...",Inequality in the distribution of income is re...,The World Bank Group's goal of promoting share...,NaN,NaN,NaN,CC BY-4.0,NaN
2,SI.DST.04TH.20,Poverty: Income distribution,Income share held by fourth 20%,NaN,Percentage share of income or consumption is t...,%,Annual,NaN,NaN,NaN,"Despite progress in the last decade, the chall...",NaN,The World Bank’s internationally comparable po...,"World Bank, Development Research Group. Data a...",Inequality in the distribution of income is re...,The World Bank Group’s goal of promoting share...,NaN,NaN,NaN,CC BY-4.0,NaN
3,SI.DST.05TH.20,Poverty: Income distribution,Income share held by highest 20%,NaN,Percentage share of income or consumption is t...,%,Annual,NaN,NaN,NaN,"Despite progress in the last decade, the chall...",NaN,The World Bank’s internationally comparable po...,"World Bank, Development Research Group. Data a...",Inequality in the distribution of income is re...,The World Bank Group’s goal of promoting share...,NaN,NaN,NaN,CC BY-4.0,NaN
4,SI.DST.10TH.10,Poverty: Income distribution,Income share held by highest 10%,NaN,Percentage share of income or consumption is t...,%,Annual,NaN,NaN,NaN,"Despite progress in the last decade, the chall...",NaN,The World Bank’s internationally comparable po...,"World Bank, Development Research Group. Data a...",Inequality in the distribution of income is re...,The World Bank Group’s goal of promoting share...,NaN,NaN,NaN,CC BY-4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,SI.SPR.PT10,Poverty: Shared prosperity,"Survey mean consumption or income per capita, ...",Mean consumption or income per capita (2011 PP...,Mean consumption or income per capita (2011 PP...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The World Bank’s internationally comparable po...,"Global Monitoring Database (GMD), World Bank P...",NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
60,SI.SPR.PT10.ZG,Poverty: Shared prosperity,Annualized growth in per capita real survey me...,The growth rate in the welfare aggregate of to...,The growth rate in the welfare aggregate of to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The World Bank’s internationally comparable po...,"Global Monitoring Database (GMD), World Bank P...",NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
61,SI.SPR.PT60,Poverty: Shared prosperity,"Survey mean consumption or income per capita, ...",Mean consumption or income per capita (2011 PP...,Mean consumption or income per capita (2011 PP...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The World Bank’s internationally comparable po...,"Global Monitoring Database (GMD), World Bank P...",NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
62,SI.SPR.PT60.ZG,Poverty: Shared prosperity,Annualized growth in per capita real survey me...,The growth rate in the welfare aggregate of to...,The growth rate in the welfare aggregate of to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The World Bank’s internationally comparable po...,"Global Monitoring Database (GMD), World Bank P...",NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
63,SP.POP.TOTL,Health: Population: Structure,"Population, total",NaN,Total population is based on the de facto defi...,NaN,Annual,NaN,NaN,Sum,Current population estimates for developing co...,NaN,Relevance to gender indicator: disaggregating ...,(1) United Nations Population Division. World ...,Population estimates are usually based on nati...,"Increases in human population, whether as a re...",NaN,NaN,NaN,CC BY-4.0,NaN

In [4]:
series.columns

Index(['Series Code', 'Topic', 'Indicator Name', 'Short definition',
       'Long definition', 'Unit of measure', 'Periodicity', 'Base Period',
       'Other notes', 'Aggregation method', 'Limitations and exceptions',
       'Notes from original source', 'General comments', 'Source',
       'Statistical concept and methodology', 'Development relevance',
       'Related source links', 'Other web links', 'Related indicators',
       'License Type', 'Unnamed: 20'],
      dtype='object')

In [5]:
series['Topic'].value_counts()

Topic
Poverty: Poverty rates           45
Poverty: Shared prosperity       10
Poverty: Income distribution      8
Health: Population: Structure     1
Name: count, dtype: int64

In [6]:
series.groupby('Topic')['Limitations and exceptions'].agg(['count', pd.Series.nunique]).style.set_caption(
    'Limitations and Exceptions')

In [7]:
country = pd.read_csv('../data/PovStatsCountry.csv', na_values='', keep_default_na=False)
print(country.shape)
country.head()

(184, 31)

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,National accounts base year,National accounts reference year,SNA price valuation,Lending category,Other groups,System of National Accounts,Alternative conversion factor,PPP survey year,Balance of Payments Manual in use,External debt Reporting status,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,NaN,South Asia,Low income,AF,2002/03,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN
1,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,NaN,Sub-Saharan Africa,Lower middle income,AO,2002,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,1991–96,2011,BPM6,Actual,Special trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2017.0,NaN
2,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,Original chained constant price data are resca...,2010,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,NaN,Rolling,BPM6,Actual,Special trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2017/18",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2017.0,NaN
3,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,NaN,Latin America & Caribbean,Upper middle income,AR,2004,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,1971–84; 2012-15,NaN,BPM6,Actual,Special trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey, 2011/12","Integrated household survey (IHS), 2016",Yes,2008,2002.0,2017.0,NaN
4,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,NaN,Europe & Central Asia,Upper middle income,AM,Original chained constant price data are resca...,2012,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,1990–95,2011,BPM6,Actual,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2016",Yes,2014,NaN,2017.0,NaN

In [8]:
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 31 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country Code                                       184 non-null    object
 1   Short Name                                         184 non-null    object
 2   Table Name                                         184 non-null    object
 3   Long Name                                          184 non-null    object
 4   2-alpha code                                       184 non-null    object
 5   Currency Unit                                      169 non-null    object
 6   Special Notes                                      61 non-null     object
 7   Region                                             169 non-null    object
 8   Income Group                                       169 non-null    object
 9   WB-2 code                                          184 non-null    object
 10  National accounts base year                        169 non-null    object
 11  National accounts reference year                   66 non-null     object
 12  SNA price valuation                                168 non-null    object
 13  Lending category                                   135 non-null    object
 14  Other groups                                       58 non-null     object
 15  System of National Accounts                        167 non-null    object
 16  Alternative conversion factor                      45 non-null     object
 17  PPP survey year                                    160 non-null    object
 18  Balance of Payments Manual in use                  167 non-null    object
 19  External debt Reporting status                     117 non-null    object
 20  System of trade                                    165 non-null    object
 21  Government Accounting concept                      141 non-null    object
 22  IMF data dissemination standard                    165 non-null    object
 23  Latest population census                           169 non-null    object
 24  Latest household survey                            136 non-null    object
 25  Source of most recent Income and expenditure data  168 non-null    object
 26  Vital registration complete                        80 non-null     object
 27  Latest agricultural census                         115 non-null    object
 28  Latest industrial data                             131 non-null    float64
 29  Latest trade data                                  180 non-null    float64
 30  Unnamed: 30                                        0 non-null      float64
dtypes: float64(3), object(28)
memory usage: 44.7+ KB

In [9]:
country['Region'].unique()

array(['South Asia', 'Sub-Saharan Africa', 'Europe & Central Asia',
       'Latin America & Caribbean', 'East Asia & Pacific',
       'North America', nan, 'Middle East & North Africa'], dtype=object)

In [10]:
# import matplotlib

In [11]:

country['Region'].value_counts(dropna=False).to_frame().style.background_gradient('cividis')

In [12]:
country['Income Group'].value_counts(dropna=False).to_frame().style.background_gradient('cividis')

In [13]:
country['is_country'] = country['Region'].notna()

In [14]:
country

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,National accounts base year,National accounts reference year,SNA price valuation,Lending category,Other groups,System of National Accounts,Alternative conversion factor,PPP survey year,Balance of Payments Manual in use,External debt Reporting status,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30,is_country
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,NaN,South Asia,Low income,AF,2002/03,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN,True
1,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,NaN,Sub-Saharan Africa,Lower middle income,AO,2002,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,1991–96,2011,BPM6,Actual,Special trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2017.0,NaN,True
2,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,Original chained constant price data are resca...,2010,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,NaN,Rolling,BPM6,Actual,Special trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2017/18",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2017.0,NaN,True
3,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,NaN,Latin America & Caribbean,Upper middle income,AR,2004,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,1971–84; 2012-15,NaN,BPM6,Actual,Special trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey, 2011/12","Integrated household survey (IHS), 2016",Yes,2008,2002.0,2017.0,NaN,True
4,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,NaN,Europe & Central Asia,Upper middle income,AM,Original chained constant price data are resca...,2012,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,1990–95,2011,BPM6,Actual,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2016",Yes,2014,NaN,2017.0,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,XKX,Kosovo,Kosovo,Republic of Kosovo,XK,Euro,NaN,Europe & Central Asia,Upper middle income,XK,Original chained constant price data are resca...,2008,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,BPM6,Actual,NaN,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2013/14","Expenditure survey/budget survey (ES/BS), 2015",NaN,2014,NaN,NaN,NaN,True
180,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,NaN,Middle East & North Africa,Low income,RY,1990,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,1990–96,2011,BPM5 (Converted into BPM6 by IMF),Actual,Special trade system,NaN,Enhanced General Data Dissemination System (e-...,2004,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2014",NaN,NaN,2012.0,2017.0,NaN,True
181,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Fiscal year end: March 31; reporting period fo...,Sub-Saharan Africa,Upper middle income,ZA,2010,2010,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,NaN,2011,BPM6,Estimate,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2016","Expenditure survey/budget survey (ES/BS), 2014/15",NaN,2007,2010.0,2017.0,NaN,True
182,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,National accounts data were rebased to reflect...,Sub-Saharan Africa,Lower middle income,ZM,2010,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 2008 System of National Accou...,1990–92,2011,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2010,"Demographic and Health Survey, 2013/14","Integrated household survey (IHS), 2015",NaN,NaN,1994.0,2017.0,NaN,True
183,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,NaN,Sub-Saharan Africa,Lower middle income,ZW,2012,NaN,Value added at basic prices (VAB),Blend,NaN,Country uses the 1993 System of National Accou...,"1991, 1998",2011,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN,True

In [15]:
country[country['Region'].isna()]['Short Name']

37     IDA countries classified as fragile situations
42                                East Asia & Pacific
43                              Europe & Central Asia
50           Fragile and conflict affected situations
70                                          IDA total
92                          Latin America & Caribbean
93                                         Low income
95                                Lower middle income
96                                Low & middle income
105                        Middle East & North Africa
107                                     Middle income
139                                        South Asia
147                                Sub-Saharan Africa
170                               Upper middle income
177                                             World
Name: Short Name, dtype: object

In [16]:
from unicodedata import lookup

In [17]:
lookup('LATIN CAPITAL LETTER E')

'E'

In [18]:
lookup("REGIONAL INDICATOR SYMBOL LETTER A")

'🇦'

In [19]:
country_codes = country[country['is_country']]['2-alpha code'].dropna().str.lower().tolist()

In [20]:
country_codes[:5]

['af', 'ao', 'al', 'ar', 'am']

In [21]:
def flag(letters):
    if pd.isna(letters) or (letters.lower() not in country_codes):
        return ''
    L0 = lookup(f'REGIONAL INDICATOR SYMBOL LETTER {letters[0]}')
    L1 = lookup(f'REGIONAL INDICATOR SYMBOL LETTER {letters[1]}')
    return L0 + L1

In [22]:
country['flag'] = [flag(code) for code in country['2-alpha code']]

In [23]:
country[['Short Name', 'flag', 'is_country']]

       Short Name flag  is_country
0     Afghanistan   🇦🇫        True
1          Angola   🇦🇴        True
2         Albania   🇦🇱        True
3       Argentina   🇦🇷        True
4         Armenia   🇦🇲        True
..            ...  ...         ...
179        Kosovo   🇽🇰        True
180         Yemen   🇾🇪        True
181  South Africa   🇿🇦        True
182        Zambia   🇿🇲        True
183      Zimbabwe   🇿🇼        True

[184 rows x 3 columns]

In [24]:
footnote = pd.read_csv('../data/PovStatsFootNote.csv')

In [25]:
footnote.head()

,CountryCode,SeriesCode,Year,DESCRIPTION,Unnamed: 4
0,AFG,SI.POV.NAHC,YR2007,Source: National Statictis and Information Aut...,NaN
1,AFG,SI.POV.NAHC,YR2011,Source: National Statictis and Information Aut...,NaN
2,AFG,SI.POV.NAHC,YR2016,Source: National Statictis and Information Aut...,NaN
3,AFG,SI.POV.NAHC.NC,YR2007,Source: National Statictis and Information Aut...,NaN
4,AFG,SI.POV.NAHC.NC,YR2011,Source: National Statictis and Information Aut...,NaN

In [26]:
footnote = footnote.drop('Unnamed: 4', axis=1)
footnote['Year'] = footnote['Year'].str[2:].astype(int)
footnote.columns = ['Country Code', 'Series Code', 'year', 'footnote']

In [28]:
footnote.head()

,Country Code,Series Code,year,footnote
0,AFG,SI.POV.NAHC,2007,Source: National Statictis and Information Aut...
1,AFG,SI.POV.NAHC,2011,Source: National Statictis and Information Aut...
2,AFG,SI.POV.NAHC,2016,Source: National Statictis and Information Aut...
3,AFG,SI.POV.NAHC.NC,2007,Source: National Statictis and Information Aut...
4,AFG,SI.POV.NAHC.NC,2011,Source: National Statictis and Information Aut...

In [29]:
data = pd.read_csv('../data/PovStatsData.csv')

In [30]:
data

,Country Name,Country Code,Indicator Name,Indicator Code,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 50
0,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PC40.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT10.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PT60.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.SPR.PCAP.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,East Asia & Pacific,EAS,Annualized growth in per capita real survey me...,SI.POV.XPND.MD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11835,Zimbabwe,ZWE,"Survey mean consumption or income per capita, ...",SI.SPR.PCAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.85,NaN,NaN,NaN,NaN,NaN,3.91,NaN,NaN,NaN
11836,Zimbabwe,ZWE,Urban poverty gap at national poverty lines (%),SI.POV.URGP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11837,Zimbabwe,ZWE,Urban poverty gap at national poverty lines (%...,SI.POV.URGP.NC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11838,Zimbabwe,ZWE,Urban poverty headcount ratio at national pove...,SI.POV.URHC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11839,Zimbabwe,ZWE,Urban poverty headcount ratio at national pove...,SI.POV.URHC.NC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
data = data.drop('Unnamed: 50', axis=1)
print(data.shape)
data.sample(3)

(11840, 50)

,Country Name,Country Code,Indicator Name,Indicator Code,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
4997,Guyana,GUY,GINI index (World Bank estimate),SI.POV.GINI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7356,Mexico,MEX,Urban poverty gap at national poverty lines (%),SI.POV.URGP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4366,France,FRA,Income share held by second 20%,SI.DST.02ND.20,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,11.9,NaN,NaN,NaN,NaN,12.7,NaN,NaN,NaN,NaN,12.5,NaN,NaN,NaN,NaN,NaN,12.8,NaN,NaN,12.8,12.9,13.2,13.2,12.7,12.6,12.7,12.4,12.5,12.6,12.7,12.7,12.8,12.9,13.0,NaN,NaN

In [32]:
data.loc[:, '1974':].isna().mean().mean()

np.float64(0.9184470475910692)

In [33]:
id_vars = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']
data_melt = pd.melt(data, id_vars=id_vars,var_name='year').dropna(subset=['value'])
data_melt['year'] = data_melt['year'].astype(int)
print(data_melt.shape)
data_melt.sample(10)

(44417, 6)

,Country Name,Country Code,Indicator Name,Indicator Code,year,value
240921,Eswatini,SWZ,Number of poor at $3.20 a day (2011 PPP) (mill...,SI.POV.LMIC.NO,1994,0.9
447564,Slovak Republic,SVK,Income share held by lowest 10%,SI.DST.FRST.10,2011,3.2
157453,Denmark,DNK,Income share held by lowest 20%,SI.DST.FRST.20,1987,9.4
514599,"Iran, Islamic Rep.",IRN,"Poverty headcount ratio at $1.90 a day, rural ...",SI.POV.DDAY.RU,2017,0.9
293339,Sao Tome and Principe,STP,"Population, total",SP.POP.TOTL,1998,137848.0
464993,Costa Rica,CRI,Poverty headcount ratio at $1.90 a day (2011 P...,SI.POV.DDAY,2013,1.6
523162,Brazil,BRA,Number of poor at $5.50 a day (2011 PPP) (mill...,SI.POV.UMIC.NO,2018,41.7
323342,Dominican Republic,DOM,Income share held by second 20%,SI.DST.02ND.20,2001,8.1
441949,El Salvador,SLV,Poverty gap at $3.20 a day (2011 PPP) (% of po...,SI.POV.LMIC.GP,2011,4.7
354445,Ukraine,UKR,Income share held by lowest 20%,SI.DST.FRST.20,2003,9.1

In [34]:
data_melt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44417 entries, 27 to 536560
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    44417 non-null  object
 1   Country Code    44417 non-null  object
 2   Indicator Name  44417 non-null  object
 3   Indicator Code  44417 non-null  object
 4   year            44417 non-null  int64
 5   value           44417 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 2.4+ MB